[package]
name = "anthropic-sdk"
version = "0.0.1"
edition = "2021"

[dependencies]
thiserror = "2.0.11"
serde = { version = "1.0.217", features = ["derive"] }
reqwest = { version = "0.12.12", features = ["json"] }